FROM registry.suse.com/bci/golang:1.26

ARG DAPPER_HOST_ARCH
ENV ARCH="$DAPPER_HOST_ARCH"

ENV DAPPER_ENV="REPO TAG DRONE_TAG CROSS"
ENV DAPPER_SOURCE="/go/src/github.com/harvester/storage-validator"
ENV DAPPER_OUTPUT="./bin"

RUN go install github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.12.2

WORKDIR ${DAPPER_SOURCE}
ENTRYPOINT ["./scripts/entry"]
CMD ["ci"]