name: Release

on:
  push:
    tags:        
      - v*

jobs:
  release:
    permissions:
      contents: write # needed to create/update the release with the assets
      id-token: write # needed for the Vault authentication
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: run ci
      run: make ci

    - name: Upload Release assets
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        if gh release view ${{ github.ref_name }} > /dev/null; then
           echo ${{ github.ref_name }} release exists
        else
           gh release create ${{ github.ref_name }} --draft --notes "Draft release for ${{ github.ref_name }}"
        fi
        gh release upload ${{ github.ref_name }} bin/storage-validator*